dist: trusty
sudo: false
language: php
php:
    - '7.0'
#    - hhvm
    - nightly

matrix:
    fast_finish: true

install:
    - composer install

script:
    - ".travis-build/phplint ."

notifications:
