alter table hms_damage_type add column active smallint not null default 1;

update hms_damage_type set active = 0 where id iN (2, 5, 82, 91, 98, 34, 104, 68, 60);



UPDATE hms_damage_type SET description = 'Light Cover- Cracked/Missing', cost = 25 where id = 1;
UPDATE hms_damage_type SET description = 'Tile replacement / holes', cost = 12 where id = 8;
UPDATE hms_damage_type SET description = 'Improper Checkout', cost = 50 where id = 105;
UPDATE hms_damage_type SET description = 'Bathroom/Shower (suite-style buildings)', cost = 30 where id = 10;
UPDATE hms_damage_type SET description = 'Carpet (Suite/Apartment)', cost = 80 where id = 12;
UPDATE hms_damage_type SET description = 'Carpet (Traditional Hall)', cost = 30 where id = 11;
UPDATE hms_damage_type SET description = 'Entire Room (Traditional Hall)', cost = 50 where id = 19;
UPDATE hms_damage_type SET description = 'Entire Suite/Apartment', cost = 150 where id = 9;
UPDATE hms_damage_type SET description = 'Housekeeping Labor Charges (per hour)', cost = 20 where id = 23;
UPDATE hms_damage_type SET description = 'Microfridge', cost = 25 where id = 14;
UPDATE hms_damage_type SET description = 'Microwave', cost = 25 where id = 16;
UPDATE hms_damage_type SET description = 'Oven', cost = 30 where id = 17;
UPDATE hms_damage_type SET description = 'Refrigerator', cost = 30 where id = 18;
UPDATE hms_damage_type SET description = 'Sink (kitchen or bathroom)', cost = 25 where id = 20;
UPDATE hms_damage_type SET description = 'Student Moving a Microfridge', cost = 25 where id = 15;
UPDATE hms_damage_type SET description = 'Tile Floor', cost = 25 where id = 21;
UPDATE hms_damage_type SET description = 'Trash Removal', cost = 25 where id = 83;
UPDATE hms_damage_type SET description = 'Vacuum', cost = 25 where id = 22;
UPDATE hms_damage_type SET description = 'Door - Broken/Split/Missing', cost = 140 where id = 25;
UPDATE hms_damage_type SET description = 'Door - Remount', cost = 40 where id = 26;
UPDATE hms_damage_type SET description = 'Paint', cost = 20 where id = 27;
UPDATE hms_damage_type SET description = 'Door Closer - Missing/Disassembled', cost = 50 where id = 37;
UPDATE hms_damage_type SET description = 'Hinges', cost = 30 where id = 28;
UPDATE hms_damage_type SET description = 'Peep Hole - Missing/damaged', cost = 15 where id = 31;
UPDATE hms_damage_type SET description = 'Replace - Broken/scratches/writing', cost = 275 where id = 32;
UPDATE hms_damage_type SET description = 'Tape Residue (per side)', cost = 25 where id = 38;
UPDATE hms_damage_type SET description = 'Writing on Door', cost = 60 where id = 39;
UPDATE hms_damage_type SET description = 'Carpet - Holes/replacement (per room)', cost = 800 where id = 40;
UPDATE hms_damage_type SET description = 'Tile - Missing/damaged', cost = 50 where id = 41;
UPDATE hms_damage_type SET description = 'Air Conditioning Unit - Missing Knob', cost = 10 where id = 42;
UPDATE hms_damage_type SET description = 'Bed - Frame Damaged/Reassemble', cost = 25 where id = 45;
UPDATE hms_damage_type SET description = 'Cabinet', cost = 25 where id = 49;
UPDATE hms_damage_type SET description = 'Chair - Damaged/Cracked/Refinish/Bar Stool Rungs', cost = 25 where id = 50;
UPDATE hms_damage_type SET description = 'Desk/Dresser & Drawers', cost = 20 where id = 55;
UPDATE hms_damage_type SET description = 'Desk/Dresser - Tape Residue', cost = 10 where id = 57;
UPDATE hms_damage_type SET description = 'Microfridge - Broken/Missing Parts', cost = 10 where id = 65;
UPDATE hms_damage_type SET description = 'Microwave - Broken/Missing Parts', cost = 50 where id = 58;
UPDATE hms_damage_type SET description = 'Recyling Bin Missing', cost = 10 where id = 106;
UPDATE hms_damage_type SET description = 'Scratched / Stained / Carved', cost = 25 where id = 77;
UPDATE hms_damage_type SET description = 'Shelves - Broken/Scratched/Missing', cost = 15 where id = 69;
UPDATE hms_damage_type SET description = 'Shower Curtain - Missing/Torn/Hooks', cost = 20 where id = 72;
UPDATE hms_damage_type SET description = 'Towel Bar - Dented/Broken/Missing', cost = 25 where id = 74;
UPDATE hms_damage_type SET description = 'Apartment / Suite', cost = 55 where id = 78;
UPDATE hms_damage_type SET description = 'App. Heights/LLC', cost = 55 where id = 80;
UPDATE hms_damage_type SET description = 'Key Not Returned - Traditional Residence Hall', cost = 55 where id = 79;
UPDATE hms_damage_type SET description = 'Cracks/Scratches/Scuffs/Pin holes', cost = 25 where id = 94;
UPDATE hms_damage_type SET description = 'Outlet Cover - Damaged/missing', cost = 15 where id = 99;
UPDATE hms_damage_type SET description = 'Paint (per wall)', cost = 40 where id = 100;
UPDATE hms_damage_type SET description = 'Tape residue (per wall)', cost = 15 where id = 103;
UPDATE hms_damage_type SET description = 'Blinds - Broken/Missing Fins', cost = 20 where id = 84;
UPDATE hms_damage_type SET description = 'Glass - Broken/Cracked', cost = 80 where id = 88;
UPDATE hms_damage_type SET description = 'Glass - Tape Residue', cost = 12 where id = 90;

select setval('hms_damage_type_seq', (select MAX(id) from hms_damage_type));

INSERT INTO  hms_damage_type VALUES (nextval('hms_damage_type_seq'), 'Ceiling', 'Tape Residue 25% or less', 35);
INSERT INTO  hms_damage_type VALUES (nextval('hms_damage_type_seq'), 'Ceiling', 'Tape Residue 25%-50%', 75);
INSERT INTO  hms_damage_type VALUES (nextval('hms_damage_type_seq'), 'Ceiling', 'Tape Residue More than 50%', 115);
INSERT INTO  hms_damage_type VALUES (nextval('hms_damage_type_seq'), 'Ceiling', 'Tear/Scratches 25% or less', 35);
INSERT INTO  hms_damage_type VALUES (nextval('hms_damage_type_seq'), 'Ceiling', 'Tear/Scratches 25%-50%', 75);
INSERT INTO  hms_damage_type VALUES (nextval('hms_damage_type_seq'), 'Ceiling', 'Tear/Scratches More than 50%', 100);
INSERT INTO  hms_damage_type VALUES (nextval('hms_damage_type_seq'), 'Cleaning', 'Furniture Dusting', 25);
INSERT INTO  hms_damage_type VALUES (nextval('hms_damage_type_seq'), 'Cleaning', 'Mirror', 12);
INSERT INTO  hms_damage_type VALUES (nextval('hms_damage_type_seq'), 'Cleaning', 'Toilet', 20);
INSERT INTO  hms_damage_type VALUES (nextval('hms_damage_type_seq'), 'Door', 'Scratches/Holes 25% or less', 25);
INSERT INTO  hms_damage_type VALUES (nextval('hms_damage_type_seq'), 'Door', 'Scratches/Holes More than 25%', 175);
INSERT INTO  hms_damage_type VALUES (nextval('hms_damage_type_seq'), 'Door', 'Lock Assembly Replacement', 325);
INSERT INTO  hms_damage_type VALUES (nextval('hms_damage_type_seq'), 'Furnishings', 'Bed - Frame Replacement', 175);
INSERT INTO  hms_damage_type VALUES (nextval('hms_damage_type_seq'), 'Furnishings', 'Bed - Mattress - Clean', 25);
INSERT INTO  hms_damage_type VALUES (nextval('hms_damage_type_seq'), 'Furnishings', 'Bed - Mattress - Replace', 125);
INSERT INTO  hms_damage_type VALUES (nextval('hms_damage_type_seq'), 'Furnishings', 'Chair - Replacement', 135);
INSERT INTO  hms_damage_type VALUES (nextval('hms_damage_type_seq'), 'Floors', 'Plank Missing/Damaged', 115);
INSERT INTO  hms_damage_type VALUES (nextval('hms_damage_type_seq'), 'Furnishings', 'Mirror - Tape Residue', 10);
INSERT INTO  hms_damage_type VALUES (nextval('hms_damage_type_seq'), 'Furnishings', 'Mirror - Replace', 15);
INSERT INTO  hms_damage_type VALUES (nextval('hms_damage_type_seq'), 'Walls', 'Hole (Other than pin/nail holes) - 1-3 (per wall)', 30);
INSERT INTO  hms_damage_type VALUES (nextval('hms_damage_type_seq'), 'Walls', 'Hole (Other than pin/nail holes) - 3-10 (per wall)', 40);
INSERT INTO  hms_damage_type VALUES (nextval('hms_damage_type_seq'), 'Walls', 'Hole (Other than pin/nail holes) - 10+ (per wall)', 60);
INSERT INTO  hms_damage_type VALUES (nextval('hms_damage_type_seq'), 'Window', 'Broken Head Rail', 30);
INSERT INTO  hms_damage_type VALUES (nextval('hms_damage_type_seq'), 'Window', 'Fin Replacement', 17);
INSERT INTO  hms_damage_type VALUES (nextval('hms_damage_type_seq'), 'Window', 'Replacment (Vertical blinds)', 175);
INSERT INTO  hms_damage_type VALUES (nextval('hms_damage_type_seq'), 'Window', 'Replacement (Mini blinds)', 65);
INSERT INTO  hms_damage_type VALUES (nextval('hms_damage_type_seq'), 'Window', 'Screen - Dirty', 25);
INSERT INTO  hms_damage_type VALUES (nextval('hms_damage_type_seq'), 'Window', 'Screen - Damaged/Bent/Replace', 75);
INSERT INTO  hms_damage_type VALUES (nextval('hms_damage_type_seq'), 'Window', 'Screen - Reinstall', 35);
