CREATE VIEW hms_hall_structure AS SELECT hms_bed.id AS bedid,
    hms_room.id AS roomid,
    hms_floor.id AS floorid,
    hms_residence_hall.id AS hallid,
    hms_bed.term AS bed_term,
    hms_room.term AS room_term,
    hms_floor.term AS floor_term,
    hms_residence_hall.term AS hall_term,
    hms_bed.bed_letter,
    hms_bed.banner_id,
    hms_bed.bedroom_label,
    hms_bed.ra_roommate,
    hms_bed.room_change_reserved,
    hms_bed.international_reserved,
    hms_room.gender_type AS room_gender,
    hms_room.reserved,
    hms_room.room_number,
    hms_room.ra,
    hms_room.private,
    hms_room.overflow,
    hms_room.default_gender,
    hms_room.offline,
    hms_room.ada,
    hms_room.hearing_impaired,
    hms_room.bath_en_suite,
    hms_room.parlor,
    hms_floor.floor_number,
    hms_floor.is_online AS floor_online,
    hms_floor.gender_type AS floor_gender,
    hms_floor.f_movein_time_id,
    hms_floor.rt_movein_time_id,
    hms_floor.t_movein_time_id,
    hms_floor.rlc_id,
    hms_floor.floor_plan_image_id,
    hms_residence_hall.banner_building_code,
    hms_residence_hall.hall_name,
    hms_residence_hall.gender_type AS hall_gender,
    hms_residence_hall.air_conditioned,
    hms_residence_hall.is_online AS hall_online,
    hms_residence_hall.meal_plan_required,
    hms_residence_hall.exterior_image_id,
    hms_residence_hall.other_image_id,
    hms_residence_hall.map_image_id,
    hms_residence_hall.room_plan_image_id,
    hms_residence_hall.assignment_notifications
   FROM hms_bed
     JOIN hms_room ON hms_bed.room_id = hms_room.id
     JOIN hms_floor ON hms_room.floor_id = hms_floor.id
     JOIN hms_residence_hall ON hms_floor.residence_hall_id = hms_residence_hall.id;