CREATE TABLE hms_student_profiles (
    id INTEGER NOT NULL,
    user_id character varying(32) NOT NULL,
    date_submitted INTEGER NOT NULL,
    arts_and_crafts smallint default 0,
    books_and_reading smallint default 0,
    cars smallint default 0,
    church_activities smallint default 0,
    collecting smallint default 0,
    computers_and_technology smallint default 0,
    dancing smallint default 0,
    fashion smallint default 0,
    fine_arts smallint default 0,
    gardening smallint default 0,
    games smallint default 0,
    humor smallint default 0,
    investing_personal_finance smallint default 0,
    movies smallint default 0,
    music smallint default 0,
    outdoor_activities smallint default 0,
    pets_and_animals smallint default 0,
    photography smallint default 0,
    politics smallint default 0,
    sports smallint default 0,
    travel smallint default 0,
    tv_shows smallint default 0,
    volunteering smallint default 0,
    alternative smallint default 0,
    ambient smallint default 0,
    beach smallint default 0,
    bluegrass smallint default 0,
    blues smallint default 0,
    classical smallint default 0,
    classic_rock smallint default 0,
    country smallint default 0,
    electronic smallint default 0,
    folk smallint default 0,
    heavy_metal smallint default 0,
    hip_hop smallint default 0,
    house smallint default 0,
    industrial smallint default 0,
    jazz smallint default 0,
    popular_music smallint default 0,
    progressive smallint default 0,
    punk smallint default 0,
    r_and_b smallint default 0,
    rap smallint default 0,
    reggae smallint default 0,
    rock smallint default 0,
    world_music smallint default 0,
    political_view smallint default 0,
    major smallint default 0,
    experience smallint default 0,
    sleep_time smallint default 0,
    wakeup_time smallint default 0,
    overnight_guests smallint default 0,
    loudness smallint default 0,
    cleanliness smallint default 0,
    study_time smallint default 0,
    free_time smallint default 0,
    primay key(id)
);

ALTER TABLE hms_assignment ADD COLUMN meal_option smallint;
ALTER TABLE hms_assignment ALTER COLUMN meal_option SET NOT NULL;

ALTER TABLE hms_assignment DROP COLUMN building_id;
