-- Transactions don't and I got tired of re-running this from the command line...
drop table hms_activity_log cascade; 
drop table hms_application cascade; 
drop table hms_assignment cascade; 
drop table hms_assignment_queue cascade; 
drop table hms_bed cascade; 
drop table hms_cached_student_info cascade; 
drop table hms_deadlines cascade; 
drop table hms_floor cascade; 
drop table hms_hall_communities cascade; 
drop table hms_learning_communities cascade; 
drop sequence hms_learning_communities_seq; 
drop table hms_learning_community_applications cascade; 
drop table hms_learning_community_assignment cascade; 
drop table hms_learning_community_floors cascade; 
drop table hms_learning_community_questions cascade; 
drop sequence hms_learning_community_questions_seq; 
drop table hms_movein_time cascade; 
drop table hms_pending_assignment cascade; 
drop table hms_pricing_tiers cascade; 
drop sequence hms_pricing_tiers_seq; 
drop table hms_residence_hall cascade; 
drop table hms_room cascade; 
drop table hms_roommate_approval cascade; 
drop table hms_roommates cascade; 
drop table hms_student cascade; 
drop table hms_student_profiles cascade; 
drop table hms_suite cascade; 
drop table hms_term cascade;
