begin;
drop table hms_activity_log cascade;
drop table hms_application_feature cascade;
drop sequence hms_application_feature_seq;
drop table hms_assignment cascade;
drop sequence hms_assignment_seq;
drop table hms_assignment_history cascade;
drop sequence hms_assignment_history_seq;
drop table hms_assignment_queue cascade;
drop table hms_banner_queue cascade;
drop sequence hms_banner_queue_seq;
drop table hms_bed cascade;
drop sequence hms_bed_seq;
drop table hms_checkin cascade;
drop sequence hms_checkin_seq;
drop table hms_contract cascade;
drop sequence hms_contract_seq;
drop table hms_damage_type cascade;
drop sequence hms_damage_type_seq;
drop table hms_eligibility_waiver cascade;
drop sequence hms_eligibility_waiver_seq;
drop table hms_fall_application cascade;
drop table hms_floor cascade;
drop sequence hms_floor_seq;
drop table hms_learning_communities cascade;
drop sequence hms_learning_communities_seq;
drop table hms_learning_community_applications cascade;
drop sequence hms_learning_community_applications_seq;
drop table hms_learning_community_assignment cascade;
drop sequence hms_learning_community_assignment_seq;
drop table hms_learning_community_questions cascade;
drop sequence hms_learning_community_questions_seq;
drop table hms_lottery_application cascade;
drop table hms_lottery_reservation cascade;
drop sequence hms_lottery_reservation_seq;
drop table hms_movein_time cascade;
drop table hms_new_application cascade;
drop sequence hms_new_application_seq;
drop table hms_package cascade;
drop table hms_package_desk cascade;
drop table hms_pending_assignment cascade;
drop table hms_permission cascade;
drop table hms_permissions cascade;
drop table hms_report cascade;
drop sequence hms_report_seq;
drop table hms_report_param cascade;
drop sequence hms_report_param_seq;
drop table hms_residence_hall cascade;
drop sequence hms_residence_hall_seq;
drop table hms_role cascade;
drop table hms_role_perm cascade;
drop table hms_room cascade;
drop sequence hms_room_seq;
drop table hms_room_change_participant cascade;
drop sequence hms_room_change_participant_seq;
drop table hms_room_change_participant_state cascade;
drop table hms_room_change_request cascade;
drop sequence hms_room_change_request_seq;
drop table hms_room_change_request_state cascade;
drop table hms_room_damage cascade;
drop sequence hms_room_damage_seq;
drop table hms_room_damage_responsibility cascade;
drop sequence hms_room_damage_responsibility_seq;
drop table hms_roommate cascade;
drop sequence hms_roommate_seq;
drop table hms_special_assignment cascade;
drop table hms_spring_application cascade;
drop table hms_student_address_cache cascade;
drop table hms_student_autocomplete cascade;
drop table hms_student_cache;
drop table hms_student_phone_cache cascade;
drop table hms_student_profiles cascade;
drop sequence hms_student_profiles_seq;
drop table hms_summer_application cascade;
drop table hms_temp_assignment;
drop table hms_term cascade;
drop table hms_user_role cascade;
drop table hms_waitlist_application;
commit;
